### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by chuchiang**
develop week2

### CODE REVIEW

**Comment by chuchiang** [comment]
老師好，以下是本週作業內容。

http://44.226.108.69:3000/

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Your code will load the same page multiple times if we scroll down and up quickly.
2. Your layout exceeds screen width in middle size of devices.
3. Text in welcome section should align to left.
4. Text in navigation bar should align to page left or right in the small devices.

未命名-2
未命名-4

**Comment by chuchiang** [comment]
老師好，已更新完畢。

http://44.226.108.69:3000/

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
